server:
  port: 0

spring:
  application:
    name: client-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/clientms
    username: postgres
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

services:
  loan:
    base-url: ${LOAN_URL:http://loan-service}
