server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-server

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/sisgr-realm

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - Authorization
                  - Content-Type
                exposedHeaders:
                  - Authorization

          routes:
            - id: inventory-service
              uri: lb://inventory-service
              predicates:
                - Path=/tool/**

            - id: loan-service
              uri: lb://loan-service
              predicates:
                - Path=/loan/**

            - id: client-service-users
              uri: lb://client-service
              predicates:
                - Path=/users/**

            - id: setting-service
              uri: lb://setting-service
              predicates:
                - Path=/settings/**

            - id: kardex-service
              uri: lb://kardex-service
              predicates:
                - Path=/kardex/**

            - id: role-service
              uri: lb://role-service
              predicates:
                - Path=/auth/**,/admin/**
