server:
  port: 0  # puerto aleatorio (cumple con "no asignación de puertos")

spring:
  application:
    name: inventory-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER:http://localhost:9090/realms/sisgr-realm}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/inventoryms
    username: postgres
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update   # crea/actualiza tablas automáticamente
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
