server:
  port: 0

spring:
  application:
    name: report-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/reportms
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

services:
  loan:
    base-url: ${LOAN_URL:http://loan-service}
  inventory:
    base-url: ${INVENTORY_URL:http://inventory-service}
  client:
    base-url: ${CLIENT_URL:http://client-service}

# Opcional: límite ranking
reports:
  top-tools-default-limit: 10
